build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: php vendor/bin/phpunit --coverage-clover=.reports/clover.xml
            coverage:
              file: .reports/clover.xml
              format: clover
checks:
  php:
      psr2_switch_declaration: true
      psr2_class_declaration: true
      no_short_open_tag: true
      deprecated_code_usage: true
      code_rating: true
filter:
  excluded_paths: [bin, docs, docker, data, tests, vendor]
tools:
  php_analyzer: true
  php_code_sniffer:
    config:
      standard: PSR12
  php_cpd:
    enabled: true
    excluded_dirs: [bin, docs, docker, data, tests, vendor]
  php_loc:
    enabled: true
    excluded_dirs: [bin, docs, docker, data, tests, vendor]
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
